apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv-extensions
spec:
  storageClassName: azure-blob
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce





  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain















